version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./app:/app
      - ./docker/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build: docker/containers/php-fpm
    expose:
      - 9000
    volumes:
      - .:/app
    links:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: auth
      MYSQL_DATABASE: auth
      MYSQL_USER: auth
      MYSQL_PASSWORD: auth
    expose:
      - 3306
